spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: khadija
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.khadija.ecommerce.kafka.PaymentNotificationRequest

application:
  config:
    product-url: http://localhost:8222/api/v1/products

server:
  port: 8060